/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.md.project.view.form.components;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import user.md.project.view.components.exception.ValidationException;
import user.md.project.view.components.validator.Validator;

/**
 *
 * @author mdjukanovic
 */
public class InputDateSeparatePanel extends javax.swing.JPanel implements GetValue {

    private Validator validator;

    /**
     * Creates new form InputDateSeparatePanel
     */
    public InputDateSeparatePanel() {
        initComponents();
        prepareComponents();
    }

    private void prepareComponents() {
        prepareDayComponent();
        prepareMonthComponent();
        prepareYearComponent();
    }

    private void prepareDayComponent() {
        for (int i = 1; i < 32; i++) {
            comboBoxDay.addItem(i);
        }
    }

    private void prepareMonthComponent() {
        for (int i = 1; i < 13; i++) {
            comboBoxMonth.addItem(i);
        }
    }

    private void prepareYearComponent() {
        for (int i = 1900; i < 2021; i++) {
            comboBoxYear.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        comboBoxDay = new javax.swing.JComboBox<>();
        comboBoxMonth = new javax.swing.JComboBox<>();
        comboBoxYear = new javax.swing.JComboBox<>();
        lblErrorValue = new javax.swing.JLabel();

        lblText.setText("Text: ");

        lblErrorValue.setForeground(new java.awt.Color(255, 51, 0));
        lblErrorValue.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblErrorValue))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblText)
                    .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Integer> comboBoxDay;
    private javax.swing.JComboBox<Integer> comboBoxMonth;
    private javax.swing.JComboBox<Integer> comboBoxYear;
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables

    public JComboBox<Integer> getComboBoxDay() {
        return comboBoxDay;
    }

    public JComboBox<Integer> getComboBoxMonth() {
        return comboBoxMonth;
    }

    public JComboBox<Integer> getComboBoxYear() {
        return comboBoxYear;
    }

    public JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public JLabel getLblText() {
        return lblText;
    }

    public void setValidator(Validator validator) {
        this.validator = validator;
    }

    @Override
    public Object getValue() throws Exception {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("d.M.yyyy");

        if (validator == null) {
            return simpleDateFormat.parse(comboBoxDay.getSelectedItem() + "." + comboBoxMonth.getSelectedItem()
                    + "." + comboBoxYear.getSelectedItem());
        }
        
        try {
            Map<String, Integer> dateValues = new HashMap<>();
            dateValues.put("day", (Integer) comboBoxDay.getSelectedItem());
            dateValues.put("month", (Integer) comboBoxMonth.getSelectedItem());
            dateValues.put("year", (Integer) comboBoxYear.getSelectedItem());

            validator.validate(dateValues);
        } catch (ValidationException ve) {
            lblErrorValue.setText(ve.getMessage());
            throw new Exception(ve.getMessage());
        }

        Date date = simpleDateFormat.parse(comboBoxDay.getSelectedItem() + "." + comboBoxMonth.getSelectedItem()
                + "." + comboBoxYear.getSelectedItem());

        return date;
    }

    public void prepareComponent(String text, String errorValue, Validator validator) {
        getLblText().setText(text);
        getLblErrorValue().setText(errorValue);
        setValidator(validator);
    }

}
