/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.md.project.view.form.components;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author mdjukanovic
 */
public class InputRadioButtonPanel extends javax.swing.JPanel implements GetValue {

    /**
     * Creates new form InputRadioButtonComponent
     */
    public InputRadioButtonPanel() {
        initComponents();
        prepareComponents();
    }

    private void prepareComponents() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtnFirstOption);
        buttonGroup.add(radiobtnSecondOption);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnFirstOption = new javax.swing.JRadioButton();
        radiobtnSecondOption = new javax.swing.JRadioButton();
        lblText = new javax.swing.JLabel();
        lblErrorValue = new javax.swing.JLabel();

        radioBtnFirstOption.setText("jRadioButton1");

        radiobtnSecondOption.setText("jRadioButton2");

        lblText.setText("Text:");

        lblErrorValue.setForeground(new java.awt.Color(255, 51, 0));
        lblErrorValue.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnFirstOption)
                        .addGap(27, 27, 27)
                        .addComponent(radiobtnSecondOption))
                    .addComponent(lblErrorValue))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnFirstOption)
                    .addComponent(radiobtnSecondOption)
                    .addComponent(lblText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblErrorValue)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblErrorValue;
    private javax.swing.JLabel lblText;
    private javax.swing.JRadioButton radioBtnFirstOption;
    private javax.swing.JRadioButton radiobtnSecondOption;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblErrorValue() {
        return lblErrorValue;
    }

    public JLabel getLblText() {
        return lblText;
    }

    public JRadioButton getRadioBtnFirstOption() {
        return radioBtnFirstOption;
    }

    public JRadioButton getRadiobtnSecondOption() {
        return radiobtnSecondOption;
    }

    @Override
    public Object getValue() throws Exception {
        lblErrorValue.setText("");
        if (!radioBtnFirstOption.isSelected() && !radiobtnSecondOption.isSelected()) {
            String error = "Polje je obavezno!";
            lblErrorValue.setText(error);
            throw new Exception(error);
        }
        return radioBtnFirstOption.isSelected() ? radioBtnFirstOption.getText() : radiobtnSecondOption.getText();
    }

    public void prepareComponent(String text, String errorValue, String firstOption, String secondOption) {
        getLblText().setText(text);
        getLblErrorValue().setText(errorValue);
        getRadioBtnFirstOption().setText(firstOption);
        getRadiobtnSecondOption().setText(secondOption);
    }

}
