/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.md.project.view.form.components;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mdjukanovic
 */
public class PersonConfigurationPanel extends javax.swing.JPanel {

    private PersonPanel personPanel;

    /**
     * Creates new form PersonConfigurationPanel
     */
    public PersonConfigurationPanel() {
        initComponents();
        prepareComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFirstname = new user.md.project.view.form.components.InputComboBoxPanel();
        inputLastname = new user.md.project.view.form.components.InputComboBoxPanel();
        inputGender = new user.md.project.view.form.components.InputComboBoxPanel();
        inputVegeterian = new user.md.project.view.form.components.InputComboBoxPanel();
        inputBirthday = new user.md.project.view.form.components.InputComboBoxPanel();
        inputMarriage = new user.md.project.view.form.components.InputComboBoxPanel();
        btnSave = new javax.swing.JButton();

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMarriage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputVegeterian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(inputFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputMarriage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputVegeterian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        List<String> componentsToShow = new ArrayList<>();
        try {
            componentsToShow.add("Firstname" + inputFirstname.getValue().toString());
            componentsToShow.add("Lastname" + inputLastname.getValue().toString());
            componentsToShow.add("Gender" + inputGender.getValue().toString());
            componentsToShow.add("Birthday" + inputBirthday.getValue().toString());
            componentsToShow.add("Marriage" + inputMarriage.getValue().toString());
            componentsToShow.add("Vegeterian" + inputVegeterian.getValue().toString());

            // Prosledi listu komponenata koje da se prikazu personPanelu
            System.out.println("Gender" + inputGender.getValue().toString());
        } catch (Exception ex) {
            Logger.getLogger(PersonConfigurationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        personPanel.changeVisibility(componentsToShow);
        this.setVisible(false);
        this.personPanel.setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private user.md.project.view.form.components.InputComboBoxPanel inputBirthday;
    private user.md.project.view.form.components.InputComboBoxPanel inputFirstname;
    private user.md.project.view.form.components.InputComboBoxPanel inputGender;
    private user.md.project.view.form.components.InputComboBoxPanel inputLastname;
    private user.md.project.view.form.components.InputComboBoxPanel inputMarriage;
    private user.md.project.view.form.components.InputComboBoxPanel inputVegeterian;
    // End of variables declaration//GEN-END:variables

    private void prepareComponents() {
        prepareFirstnameComponent();
        prepareLastnameComponent();
        prepareGenderComponent();
        prepareMarriageComponent();
        prepareBirthdayComponent();
        prepareVegeterianComponent();
    }

    private void prepareFirstnameComponent() {
        List<String> firstnameComponents = new ArrayList<>();
        firstnameComponents.add("InputTextFieldPanel");
        inputFirstname.prepareComponent("Firstname: ", "", firstnameComponents);
    }

    private void prepareLastnameComponent() {
        List<String> lastnameComponents = new ArrayList<>();
        lastnameComponents.add("InputTextFieldPanel");
        inputLastname.prepareComponent("Lastname: ", "", lastnameComponents);
    }

    private void prepareGenderComponent() {
        List<String> genderComponents = new ArrayList<>();
        genderComponents.add("InputTextFieldPanel");
        genderComponents.add("InputComboBoxPanel");
        inputGender.prepareComponent("Gender: ", "", genderComponents);
    }

    private void prepareMarriageComponent() {
        List<String> marriageComponents = new ArrayList<>();
        marriageComponents.add("InputTextFieldPanel");
        marriageComponents.add("InputComboBoxPanel");
        inputMarriage.prepareComponent("Married: ", "", marriageComponents);
    }

    private void prepareBirthdayComponent() {
        List<String> birthdayComponents = new ArrayList<>();
        birthdayComponents.add("InputTextFieldPanel");
        birthdayComponents.add("InputDateSeparatePanel");
        inputBirthday.prepareComponent("Birthday: ", "", birthdayComponents);
    }

    private void prepareVegeterianComponent() {
        List<String> vegeterianComponents = new ArrayList<>();
        vegeterianComponents.add("InputRadioButtonPanel");
        inputVegeterian.prepareComponent("Vegeterian: ", "", vegeterianComponents);
    }

    public void setPersonPanel(PersonPanel personPanel) {
        this.personPanel = personPanel;
    }
}
