/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.md.project.view.form;

/**
 *
 * @author mdjukanovic
 */
public class Person extends javax.swing.JFrame {

    /**
     * Creates new form Person
     */
    public Person() {
        initComponents();
        // VISIBILITY PANELA
        prepareComponents();
    }

    private void prepareComponents() {
        inputPersonConfiguration.setVisible(false);
        inputPerson.setVisible(false);
        
        this.inputPersonConfiguration.setPersonPanel(this.inputPerson);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputPersonConfiguration = new user.md.project.view.form.components.PersonConfigurationPanel();
        inputPerson = new user.md.project.view.form.components.PersonPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPersonConfiguration = new javax.swing.JMenu();
        menuItemPersonConfiguration = new javax.swing.JMenuItem();
        menuPerson = new javax.swing.JMenu();
        menuItemAdd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(inputPersonConfiguration, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel1.add(inputPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(jPanel1, "card2");

        menuPersonConfiguration.setText("PersonConfiguration");

        menuItemPersonConfiguration.setText("PersonConfiguration");
        menuItemPersonConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPersonConfigurationActionPerformed(evt);
            }
        });
        menuPersonConfiguration.add(menuItemPersonConfiguration);

        jMenuBar1.add(menuPersonConfiguration);

        menuPerson.setText("Person");

        menuItemAdd.setText("Add");
        menuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddActionPerformed(evt);
            }
        });
        menuPerson.add(menuItemAdd);

        jMenuBar1.add(menuPerson);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemPersonConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPersonConfigurationActionPerformed
        inputPersonConfiguration.setVisible(true);
        inputPerson.setVisible(false);
    }//GEN-LAST:event_menuItemPersonConfigurationActionPerformed

    private void menuItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddActionPerformed
        inputPerson.setVisible(true);
        inputPersonConfiguration.setVisible(false);

    }//GEN-LAST:event_menuItemAddActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private user.md.project.view.form.components.PersonPanel inputPerson;
    private user.md.project.view.form.components.PersonConfigurationPanel inputPersonConfiguration;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemAdd;
    private javax.swing.JMenuItem menuItemPersonConfiguration;
    private javax.swing.JMenu menuPerson;
    private javax.swing.JMenu menuPersonConfiguration;
    // End of variables declaration//GEN-END:variables

}
